server:
  port: 80

eureka:
  client:

    register-with-eureka: true
    fetch-registry: true
    service-url:     #所有Entity别名类所在包
#      defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


spring:
  application:
    name: cloud-order-server